# Generated by Django 3.1.2 on 2021-01-17 01:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entrevistador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('empresa', models.CharField(max_length=50)),
                ('opinion', models.TextField()),
                ('mejorar', models.TextField()),
                ('fecha', models.DateField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': 'Entrevistador',
                'verbose_name_plural': 'Entrevistadores',
                'db_table': 'Entrevistadores',
                'ordering': ['fecha'],
            },
        ),
    ]
